DROP ROLE MANAGER;
DROP ROLE LOGISTICSTEAM;
DROP ROLE SALESMANAGER;
DROP ROLE SELLER;
DROP ROLE USER_ROLE;

DROP PACKAGE BODY PKG_USER;
DROP PACKAGE PKG_USER;

DROP PACKAGE BODY PKG_SALESMANAGER;
DROP PACKAGE PKG_SALESMANAGER;

DROP PACKAGE BODY PKG_MANAGER;
DROP PACKAGE PKG_MANAGER;

DROP PACKAGE BODY PKG_LOGISTICSTEAM;
DROP PACKAGE PKG_LOGISTICSTEAM;

DROP PACKAGE BODY PKG_SELLER;
DROP PACKAGE PKG_SELLER;
